import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { CookiesProvider } from "next-client-cookies/server";
import { getCookies } from "next-client-cookies/server";

import { ToastContainer } from 'react-toastify';

import "./globals.scss";

import {api} from "@/lib/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = await getCookies();
  const language = cookies.get("language") || "en";
  const theme = cookies.get("theme") || "light";

  return (
    <CookiesProvider>
      <html lang={language} className={theme}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <ToastContainer style={{ zIndex: 99999999 }} />
        </body>
      </html>
    </CookiesProvider>
  );
}
